package ai.love.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ai.love.model.NoteEnity;

import ai.love.model.NoteEnityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteEnityDaoConfig;

    private final NoteEnityDao noteEnityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteEnityDaoConfig = daoConfigMap.get(NoteEnityDao.class).clone();
        noteEnityDaoConfig.initIdentityScope(type);

        noteEnityDao = new NoteEnityDao(noteEnityDaoConfig, this);

        registerDao(NoteEnity.class, noteEnityDao);
    }
    
    public void clear() {
        noteEnityDaoConfig.clearIdentityScope();
    }

    public NoteEnityDao getNoteEnityDao() {
        return noteEnityDao;
    }

}
